### ISSUE TITLE
百度云盘分享文件已过期

### ISSUE THREAD

**Issue by SWPU-like** [WJmodels/CMGNet#1]
哈喽，百度云盘分享文件过期了，请问可否重新分享一下呀？
非常感谢！

**Comment by WJmodels** [comment]
抱歉才看到您的消息，以下是云盘链接，请您查看下载


通过百度网盘分享的文件：mcgnet_g....zip
链接：https://pan.baidu.com/s/17Fdwz0oCWYv034T_r_D7XQ 
提取码：779a 
复制这段内容打开「百度网盘APP 即可获取」


| |
wjmodel2023
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年7月27日 15:16 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [WJmodels/CMGNet] 百度云盘分享文件已过期 (Issue #1) |

哈喽，百度云盘分享文件过期了，请问可否重新分享一下呀？
非常感谢！

**Comment by SWPU-like** [comment]
> 抱歉才看到您的消息，以下是云盘链接，请您查看下载通过百度网盘分享的文件：mcgnet_g....zip 链接：https://pan.baidu.com/s/17Fdwz0oCWYv034T_r_D7XQ 提取码： 779a 复制贝尔内容打开「百度网盘APP即可获取」 | | wjmodel2023 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年7月27日 15:16 | | 营养 | ***@***.***> | | 抄送人 | ***@***.***> | | 主题 | [WJmodels/CMGNet] 百度云盘分享文件已过期 (Issue #1 ) | 哈喽，百度云盘分享文件过期了，请问可否重新分享呀？非常感谢！一下 — 直接回复此邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您订阅了该主题。消息 ID：***@***.***>
非常感谢您的分享！！！祝生活愉快！！！
